#!/usr/bin/env bash
# =============================================================
#  detect-lan-ip.sh — Resolve this machine's Wi‑Fi/LAN IPv4
#  Writes docker/.env.lan AND updates LAN_IP in docker/.env so
#  Traefik Host rules survive rebuilds without a separate file.
# =============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${DOCKER_DIR}/.env"
LAN_ENV_FILE="${DOCKER_DIR}/.env.lan"

LAN_IP=""
PINNED=false

if [[ -f "${ENV_FILE}" ]]; then
  if grep -qE '^LAN_IP_PINNED=(true|1|yes)' "${ENV_FILE}"; then
    PINNED=true
  fi
  OVERRIDE="$(grep -E '^LAN_IP=' "${ENV_FILE}" 2>/dev/null | cut -d= -f2- | tr -d '"' | tr -d "'" | xargs || true)"
  if [[ "${PINNED}" == "true" && -n "${OVERRIDE}" && "${OVERRIDE}" != "auto" ]]; then
    LAN_IP="${OVERRIDE}"
  fi
fi

detect_ip() {
  local ip=""

  if command -v route >/dev/null 2>&1 && command -v ipconfig >/dev/null 2>&1; then
    local iface
    iface="$(route -n get default 2>/dev/null | awk '/interface:/{print $2; exit}')"
    if [[ -n "${iface}" ]]; then
      ip="$(ipconfig getifaddr "${iface}" 2>/dev/null || true)"
    fi
    if [[ -z "${ip}" ]]; then
      for candidate in en0 en1 en2; do
        ip="$(ipconfig getifaddr "${candidate}" 2>/dev/null || true)"
        [[ -n "${ip}" ]] && break
      done
    fi
  fi

  if [[ -z "${ip}" ]] && command -v ip >/dev/null 2>&1; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
  fi

  if [[ -z "${ip}" ]]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi

  echo "${ip}"
}

if [[ -z "${LAN_IP}" ]]; then
  LAN_IP="$(detect_ip)"
fi

if [[ -z "${LAN_IP}" ]]; then
  echo "Warning: could not detect LAN IP. Falling back to 127.0.0.1" >&2
  LAN_IP="127.0.0.1"
fi

cat > "${LAN_ENV_FILE}" <<EOF
# Auto-generated by scripts/detect-lan-ip.sh — do not edit by hand
LAN_IP=${LAN_IP}
EOF

# Persist into .env so rebuilds / plain "docker compose up" keep the correct Host rule
if [[ -f "${ENV_FILE}" ]]; then
  if grep -qE '^LAN_IP=' "${ENV_FILE}"; then
    # Replace existing LAN_IP=... (including commented auto placeholder lines that were uncommented)
    if grep -qE '^LAN_IP=' "${ENV_FILE}"; then
      sed -i.bak -E "s|^LAN_IP=.*|LAN_IP=${LAN_IP}|" "${ENV_FILE}"
      rm -f "${ENV_FILE}.bak"
    fi
  else
    printf '\n# Auto-updated by start.sh / detect-lan-ip.sh\nLAN_IP=%s\n' "${LAN_IP}" >> "${ENV_FILE}"
  fi
fi

echo "${LAN_IP}"
